// Test definitions. Do NOT edit this file!

#include <tuple>

//#define CATCH_CONFIG_MAIN // defines main() automatically
#include "lib/catch.hpp"
#include "sudoku.hpp"
#include <string.h>
#include <math.h>


// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Test1", "[h]")
{
    float expected = -1.0;
    int n = 0;
    INFO("Testing default (h(0) = 0)");
    REQUIRE(fabs(expected - h(n)) < 0.01 );
}
